---
# Persona Scope: Cluster operator
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: infra
  namespace: infra  
spec:
  gatewayClassName: cilium  #which of the available gateway classes we'll be using.
  listeners:
  - protocol: HTTP # Lets just listen for HTTP 
    port: 80 # listen on port 80
    name: web-gw
    hostname: infra.empire.galactic.gov 
    # Can only attach HTTPRoutes from the same namespace
    allowedRoutes:
      namespaces:
        from: Same
  - protocol: HTTP # Lets just listen for HTTP 
    port: 80 # listen on port 80
    name: deathstar-gw
    hostname: deathstar.empire.galactic.gov 
    # Can only attach HTTPRoutes from the deathstar namespace
    allowedRoutes:
      namespaces:
        #from: All
        from: Selector
        selector:
          matchLabels:
            hostname: deathstar.empire.galactic.gov
  - protocol: HTTP # Lets just listen for HTTP 
    port: 80 # listen on port 80
    name: eop-gw
    hostname: eop.empire.galactic.gov 
    # Can only attach HTTPRoutes from the deathstar namespace
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            hostname: eop.empire.galatic.gov
